
#version 450
#extension GL_EXT_shader_atomic_float : enable
layout(local_size_x = 32, local_size_y = 1, local_size_z = 1) in;

#include "pushConstants.glsl"
#include "bufferBindings.glsl"
#include "random.glsl"
#include "hash.glsl"
#include "util.glsl"

void main() {
    const uint antID    = gl_GlobalInvocationID.x;
    const uint antCount = pushConstants.antCount;

    // Check if ID is in bounds
    if (antID >= antCount)
        return;

    // Reference necessary values
    const uint  dim                      = pushConstants.dim;
    const float pheromonePower           = pushConstants.pheromonePower;
    const float exploitationProbability  = pushConstants.exploitationProbability;
    const float localEvaporation         = pushConstants.localEvaporation;
    const float initialPheromoneStrength = pushConstants.initialPheromoneStrength;

    const uint antSpecificValuesIndex = antID * dim;

    // Init random number generator
    const uint seed = antID + (pushConstants.iteration * 1966087u) + (pushConstants.seed * 2654435761u);
    PCGState rng;
    rng.state = hash(seed);
    
    // Reset path lengths
    pathLengths.values[antID] = 0u;
    
    // Set random starting node
    const uint swapToStart = pcg_next(rng) % dim;
    swap(visited.indices[antSpecificValuesIndex], visited.indices[antSpecificValuesIndex + swapToStart]);

    for (uint seq = 1; seq < dim; seq++) {
        // Index of the current visited node
        uint currentVisitedIndex = visited.indices[antSpecificValuesIndex + seq - 1];
        uint matrixRow = currentVisitedIndex * dim;

        // Find the next node to visit
        uint nextVisitedIndex = antSpecificValuesIndex + seq;
        float q = pcg_nextf(rng);

        if (q < exploitationProbability) {
            float maxScore = -1.0f;

            for (uint notVisited = seq; notVisited < dim; notVisited++) {
                uint notVisitedIndex = antSpecificValuesIndex + notVisited;
                uint matrixIndex = matrixRow + visited.indices[notVisitedIndex];
                float score = heuristics.matrix[matrixIndex] * pheromones.matrix[matrixIndex];

                if (maxScore < score) {
                    maxScore = score;
                    nextVisitedIndex = notVisitedIndex;
                }
            }
        } else {
            float sumScores = 0.0f;

            for (uint notVisited = seq; notVisited < dim; notVisited++) {
                uint notVisitedIndex = antSpecificValuesIndex + notVisited;
                uint matrixIndex = matrixRow + visited.indices[notVisitedIndex];
                float score = heuristics.matrix[matrixIndex] * pheromones.matrix[matrixIndex];

                sumScores += score;
                probabilisticWeights.values[antSpecificValuesIndex + notVisited] = score;
            }

            float r = pcg_nextf(rng) * sumScores;

            uint nextIndex = seq;
            while (nextIndex < dim) {
                r -= probabilisticWeights.values[antSpecificValuesIndex + nextIndex];

                if (r <= 0) 
                    break;

                nextIndex++;
            }

            nextVisitedIndex = antSpecificValuesIndex + nextIndex;
        }

        // Get next node to visit up front
        // Visited looks like
        // 10 5 2 8 6 1 4 3 7 9 11 50 21 ...
        // < visited | not visited >
        swap(visited.indices[antSpecificValuesIndex + seq], visited.indices[nextVisitedIndex]);
        uint next = visited.indices[antSpecificValuesIndex + seq];

        // Update local pheromone
        uint i1 = currentVisitedIndex + next * dim;
        uint i2 = next + currentVisitedIndex * dim;
        
        float delta = (1.0f - localEvaporation) * pheromones.matrix[i1] \
                     + localEvaporation * initialPheromoneStrength      \
                     - pheromones.matrix[i1];

        pheromones.matrix[i1] += delta;
        pheromones.matrix[i2] += delta;
    
        pathLengths.values[antID] += edgeWeights.matrix[i1];
    }

    // Close the Hamiltonian cycle (return to start)
    uint lastNode = visited.indices[antSpecificValuesIndex + dim - 1u];
    uint firstNode = visited.indices[antSpecificValuesIndex];
    pathLengths.values[antID] += edgeWeights.matrix[firstNode + lastNode * dim];
}